using System.Linq;
using FacetedWorlds.Reversi.Model;
using UpdateControls;
using UpdateControls.Correspondence.POXClient;

namespace FacetedWorlds.Reversi.Presenters
{
    public class POXConfigurationProvider : IPOXConfigurationProvider
    {
        private Identity _identity;

        #region Independent properties
        // Generated by Update Controls --------------------------------
        private Independent _indIdentity = new Independent();

        public Identity Identity
        {
            get { _indIdentity.OnGet(); return _identity; }
            set { _indIdentity.OnSet(); _identity = value; }
        }
        // End generated code --------------------------------
        #endregion

        public POXConfiguration Configuration
        {
            get
            {
                //return new POXConfiguration("http://facetedworlds.com/correspondence_server_web/pox", "FacetedWorlds.Reversi", "api key");
                return new POXConfiguration("http://10.0.1.7:11821/correspondence_server_web/pox", "FacetedWorlds.Reversi", "api key");
            }
        }

        public bool IsToastEnabled
        {
            get { return Identity == null ? false : !Identity.IsToastNotificationDisabled.Any(); }
        }
    }
}
