using UpdateControls;

namespace FacetedWorlds.Reversi.ViewModel
{
    public class ChatNavigationModel
    {
        private string _messageBody;

        #region Independent properties
        // Generated by Update Controls --------------------------------
        private Independent _indMessageBody = new Independent();

        public string MessageBody
        {
            get { _indMessageBody.OnGet(); return _messageBody; }
            set { _indMessageBody.OnSet(); _messageBody = value; }
        }
        // End generated code --------------------------------
        #endregion
    }
}
