using System;
using UpdateControls;
using FacetedWorlds.Reversi.Model;

namespace FacetedWorlds.Reversi.ViewModel
{
    public class MachineNavigationModel
    {
        private string _userName;
        private string _opponentName;
        private Player _selectedPlayer;

        #region Independent properties
        // Generated by Update Controls --------------------------------
        private Independent _indSelectedPlayer = new Independent();
        private Independent _indOpponentName = new Independent();
        private Independent _indUserName = new Independent();

        public string UserName
        {
            get { _indUserName.OnGet(); return _userName; }
            set { _indUserName.OnSet(); _userName = value; }
        }

        public string OpponentName
        {
            get { _indOpponentName.OnGet(); return _opponentName; }
            set { _indOpponentName.OnSet(); _opponentName = value; }
        }

        public Player SelectedPlayer
        {
            get { _indSelectedPlayer.OnGet(); return _selectedPlayer; }
            set { _indSelectedPlayer.OnSet(); _selectedPlayer = value; }
        }
        // End generated code --------------------------------
        #endregion
    }
}
